"""enrich transaction and add simulation config

Revision ID: c23e80e28b2f
Revises: 
Create Date: 2026-01-09 18:36:34.633885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23e80e28b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('min_trade_amount', sa.Float(), nullable=False),
    sa.Column('max_position_size_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('commission_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('commission_amount')
        batch_op.drop_column('asset_name')

    op.drop_table('simulation_config')
    # ### end Alembic commands ###
